# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/shahriar/IDEAS/papers/remote-attestation/implementations/hardware/raz/raz.cache/wt [current_project]
set_property parent.project_path /home/shahriar/IDEAS/papers/remote-attestation/implementations/hardware/raz/raz.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib /home/shahriar/IDEAS/papers/remote-attestation/implementations/hardware/raz/raz.srcs/sources_1/new/dec512.v
read_xdc /home/shahriar/IDEAS/papers/remote-attestation/implementations/hardware/raz/raz.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files /home/shahriar/IDEAS/papers/remote-attestation/implementations/hardware/raz/raz.srcs/constrs_1/new/const.xdc]

synth_design -top dec512 -part xc7a200tfbg676-2 -directive AreaOptimized_high -control_set_opt_threshold 1
write_checkpoint -noxdef dec512.dcp
catch { report_utilization -file dec512_utilization_synth.rpt -pb dec512_utilization_synth.pb }
