dist: trusty
language: node_js
node_js:
  - "11"
install:
  - npm ci
  - cp .env.example .env
  - travis_wait 30 npm run build:circuit
  - npm run build:contract
script:
  - npm run test
  - npm run eslint
